format = """
$username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$fossil_branch$fossil_metrics$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$docker_context$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$typst$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$aws$gcloud$openstack$azure$nats$direnv$mise$crystal$sudo$cmd_duration$line_break\
$jobs$status$os$container$netns$shell$env_var$custom$character"""
right_format = '$memory_usage$battery$time'

[character]
format = '$symbol '
success_symbol = '[](fg:#5BCEFA)[](bg:#F5A9B8 fg:#5BCEFA)[](bg:#FFFFFF fg:#F5A9B8)[](bg:#F5A9B8 fg:#FFFFFF)[](bg:#5BCEFA fg:#F5A9B8)[](fg:#5BCEFA)'
error_symbol = '[](fg:#5BCEFA)[](bg:#F5A9B8 fg:#5BCEFA)[](bg:#FFFFFF fg:#F5A9B8)[](bg:#F5A9B8 fg:#FFFFFF)[](bg:#5BCEFA fg:#F5A9B8)[](fg:#5BCEFA)'

[[battery.display]]
threshold = 100
style = 'bold green'

[battery]
format = '[$symbol$percentage]($style) / '

[memory_usage]
disabled = false
format = '[$ram_pct]($style) / '
threshold = -1
symbol = ''

[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'
utc_time_offset = '+8'

[env_var.ASCIINEMA_REC]
format = '[⬤ REC]($style) '
style = 'bold yellow'

[kubernetes]
disabled = false
detect_folders = [ 'infra' ]
